### ISSUE TITLE
Add Support for Sandbox execution

### ISSUE THREAD

**Issue by DavidLambauer** [run-as-root/magento-cli-auto-proxy#14]
Turns out that the `cli_arg_auto_proxy_di.xml` is not added to the sandbox directories. Whenever you run integration tests via `php bin/magento dev:tests:run integration` or via `cd dev/tests/integration && php ../../../vendor/bin/phpunit -c ../../../phpunit-integration.xml` Magento create temporary directories under `dev/tests/integration/tmp/sandox-....`. These sandbox directories don't include the `cli_arg_auto_proxy_di.xml`, so the classic `flag` error occurs. 

In `\Magento\TestFramework\Application::copyAppConfigFiles`, the pattern shows that we could place the `cli_arg_auto_proxy_di.xml` into `app/etc/SOMEDIR/di.xml` and it would work for the sandbox tests. 

This needs to be tested for the non-sandbox execution though.

**Comment by vpodorozh** [comment]
resolved with https://github.com/run-as-root/magento-cli-auto-proxy/pull/15
